import {
  LayoutDashboard,
  MapPin,
  HelpCircle,
  Settings,
  Star,
  Mail,
  Lock,
  Users,
  Package,
  Info,
  Route,
  Globe,
  Calculator,
  Images,
} from "lucide-react";

export const NAV = [
  { id: "dashboard",      label: "Dashboard",      href: "/dashboard",      icon: LayoutDashboard },
  { id: "hero-images",    label: "Hero Carousel",  href: "/hero-images",    icon: Images },
  // { id: "clients",        label: "Partners",       href: "/clients",        icon: Users },
  { id: "stations",       label: "Stations",       href: "/stations",       icon: MapPin },
  // { id: "products",       label: "Products",       href: "/products",       icon: Package },
  { id: "testimonials",   label: "Testimonials",   href: "/testimonials",   icon: Star },
  { id: "faq",            label: "FAQ",            href: "/faq",            icon: HelpCircle },
  { id: "about",          label: "About Us",       href: "/about",          icon: Info },
  { id: "journey",        label: "Our Journey",    href: "/journey",        icon: Route },
  { id: "contact",        label: "Contact",        href: "/contact",        icon: Mail },
  { id: "site-settings",  label: "Site Settings",  href: "/site-settings",  icon: Globe },
  { id: "calculator-settings", label: "Calculators", href: "/calculator-settings", icon: Calculator },
  { id: "seo-settings",   label: "SEO Settings",   href: "/seo-settings",   icon: Settings },
  { id: "privacy-policy", label: "Privacy Policy", href: "/privacy-policy", icon: Lock },
];
